### ISSUE TITLE
Drop Ensure Clobber Patch

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/pip-feedstock#17]
As I had mentioned in https://github.com/conda-forge/pip-feedstock/pull/11#issuecomment-394255902 , the local patch being applied needs to be dropped starting 18.0, since it is already being taken care of by https://github.com/pypa/pip/pull/5405

You would save a syscall :)

**Comment by ocefpaf** [comment]
Thanks @nehaljwani I did the patch updated but did not pay attention that the version we have we could drop it. I'll do that in a moment.
