### ISSUE TITLE
noarch package possible?

### ISSUE THREAD

**Issue by marscher** [conda-forge/pip-feedstock#29]
For deprecated (but still used) Python versions it would be very nice to have a pip version in place, which supports pep517. Older versions of pip contains bugs concerning pep517 rendering it effectively useless for that manner.

**Comment by ocefpaf** [comment]
The only document reason I found for it is https://github.com/conda-forge/pip-feedstock/pull/12#issuecomment-404252165

However, you can do a `pip update pip` in your env to get the latest and hopefully circumvent that.
