### ISSUE TITLE
pip 19.1.1 in all platforms

### ISSUE THREAD

**Issue by Juanlu001** [conda-forge/pip-feedstock#30]
pip 19.1.1 was only built for Windows 64bit: https://anaconda.org/conda-forge/pip/files?version=19.1.1

**Comment by ocefpaf** [comment]
I restarted the CIs. Let's see if that solves the problem.

**Comment by jakirkham** [comment]
Looks like it did. Please let us know if some were missed though.

**Comment by jakirkham** [comment]
<img width="987" alt="Screen Shot 2019-06-04 at 11 13 46 AM" src="https://user-images.githubusercontent.com/3019665/58891077-e032ad00-86b9-11e9-8376-8b4046ea8d8c.png">
